### ISSUE TITLE
Get in trouble when run run_crslab.py 

### ISSUE THREAD

**Issue by peterpan23** [RUCAIBox/CRSLab#11]
AssertionError: [ Checksum for redial_nltk.zip from
http://d0.ananas.chaoxing.com/download/417f6ac16282e4910fc93973e954ab42?fn=nltk
does not match the expected checksum. Please try again. ]

How to fix it!

**Comment by peterpan23** [comment]
奇怪了，我用的就是最新版的，最新版是CRSLab v0.1.1吧？








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RUCAIBox/CRSLab"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月10日(星期三) 下午5:04
收件人:&nbsp;"RUCAIBox/CRSLab"<CRSLab@noreply.github.com&gt;;
抄送:&nbsp;"fanghui_mju"<405899204@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [RUCAIBox/CRSLab] Get in trouble when run run_crslab.py  (#11)





 
We have changed the location of data storage, use the latest version and the problem will be solved.

**Comment by wxl1999** [comment]
Sorry, we just make the change in the GitHub repo without release, because there is still some improvement to do for the next planned version.

**Comment by peterpan23** [comment]
You means the next planned version would resolve my problem.
But If I want to run your CRSLab very urgently, can you help me in other way?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RUCAIBox/CRSLab"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月10日(星期三) 下午5:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RUCAIBox/CRSLab] Get in trouble when run run_crslab.py  (#11)





 
Sorry, we just make the change in the GitHub repo without release, because there is still some improvement to do for the next planned version.

**Comment by wxl1999** [comment]
Currently, you can just pull the latest version in GitHub repo.

**Comment by peterpan23** [comment]
Thank you! Where I can obtain the&nbsp;tutorial about how to pull the lastest version in GitHub repo?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RUCAIBox/CRSLab"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月13日(星期六) 下午4:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RUCAIBox/CRSLab] Get in trouble when run run_crslab.py  (#11)





 
Currently, you can just pull the latest version in GitHub repo.

**Comment by wxl1999** [comment]
Try baidu or google? There are so many good tutorials, you can find the one that suits you best.

**Comment by peterpan23** [comment]
Thank you.I have a try.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RUCAIBox/CRSLab"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月13日(星期六) 下午4:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RUCAIBox/CRSLab] Get in trouble when run run_crslab.py  (#11)





 
Try baidu or google? There are so many good tutorials, you can find the one that suits you best.
