### ISSUE TITLE
无法下载 cc.zh.300.zip

### ISSUE THREAD

**Issue by peterpan23** [RUCAIBox/CRSLab#15]
无法下载 cc.zh.300.zip，AssertionError: Checkksum for cc.zh.300.zip，如何解决？

**Comment by ToheartZhang** [comment]
Maybe it's because you ran the program before but terminated it in the middle of the download. If so, you can delete the corresponding file in the folder `./data` and run again.

**Comment by wxl1999** [comment]
Also make sure that the version is the latest as the repo.

**Comment by kmphuang** [comment]
请问解决了吗，我也遇到了这个问题

**Comment by wxl1999** [comment]
@kmphuang 您好，我已经在最新的 issue 里回复你了，用目前仓库里最新的版本就可以。
