### ISSUE TITLE
There are any pretrain model to test? And question about Human-machine interaction interfaces

### ISSUE THREAD

**Issue by saladcat** [RUCAIBox/CRSLab#16]
thanks you for sharing your awesome works! I have some question about this repo.

I am the first year master student and need to do a project about IR/RecSys/Search Engine for my course final project.I have seen your Ads. in somewhere and I think a Conversation Recommendation Demo is really COOL for this project. 

but we meet some trouble here.

1. I have NO GPU to train the whole model, could you share some PreTrain model for us to test. Thanks 
2. I see the describe in README.MD 
"Human-machine interaction interfaces: We provide flexible human-machine interaction interfaces for researchers to conduct qualitative analysis." 
is that mean this interface is something like terminal and recommendation version of Siri?

**Comment by wxl1999** [comment]
Thanks for your feedback!
1. We will take this into consideration and release some models with superior performance in the future.
2. You can understand in this way and we will further improve this feature.
