### ISSUE TITLE
Consultation for the bugs in Human-machine interaction interfaces 

### ISSUE THREAD

**Issue by peterpan23** [RUCAIBox/CRSLab#20]
I wonder to  know when  to fix the bugs in Human-machine interaction interfaces since the release of  latest version 0.1.2? Because we want to conduct qualitative analysis urgently.

**Comment by Zilize** [comment]
We have so far only implemented the human-machine interaction interface on the CRS model TGReDial.

**Comment by Zilize** [comment]
Hi,

We have so far only implemented the human-machine interaction interface on the CRS model TGReDial. If you need to conduct qualitative analysis, maybe you can complete your own interface as if which was already implemented in TGReDial System.

https://github.com/RUCAIBox/CRSLab/blob/a20d28296e36699e15629d4968c09d85ed0bda25/crslab/system/tgredial.py#L293
