### ISSUE TITLE
Is it normal to be so slow in train phase？

### ISSUE THREAD

**Issue by saladcat** [RUCAIBox/CRSLab#21]
I just run 
`python run_crslab.py --config config/crs/tgredial/tgredial.yaml --save_data --save_system -g 3`
but it lag at this step, it almost cost 9 hours to process data
> INFO     | crslab.data.dataloader.base:get_data:54 - [Finish dataset process before batchify]

it is realy slow in the step for training. that means I need a more powerful cpu or disk? does anyone slow as I am?

**Comment by Zilize** [comment]
Could you please provide the full log for this command? The data process step just cost 10 seconds on my machine.
<img width="1161" alt="截屏2021-04-18 下午5 28 17" src="https://user-images.githubusercontent.com/43633644/115140758-7e8c4980-a06b-11eb-8fec-744c4f7355f4.png">

**Comment by saladcat** [comment]
> Could you please provide the full log for this command? The data process step just cost 10 seconds on my machine.
> <img alt="截屏2021-04-18 下午5 28 17" width="1161" src="https://user-images.githubusercontent.com/43633644/115140758-7e8c4980-a06b-11eb-8fec-744c4f7355f4.png">

Log 
![image](https://user-images.githubusercontent.com/22851795/115140874-11c57f00-a06c-11eb-9348-8b6e7c7319a4.png)

cpu usage, this process exhaust all my cpus.
![image](https://user-images.githubusercontent.com/22851795/115140892-27d33f80-a06c-11eb-949d-1ab96eb8d7d2.png)

My cpu 
`
$ cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c
     32  Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
`

**Comment by Zilize** [comment]
> > Could you please provide the full log for this command? The data process step just cost 10 seconds on my machine.
> > <img alt="截屏2021-04-18 下午5 28 17" width="1161" src="https://user-images.githubusercontent.com/43633644/115140758-7e8c4980-a06b-11eb-8fec-744c4f7355f4.png">
> 
> Log
> ![image](https://user-images.githubusercontent.com/22851795/115140874-11c57f00-a06c-11eb-9348-8b6e7c7319a4.png)
> 
> cpu usage, this process exhaust all my cpus.
> ![image](https://user-images.githubusercontent.com/22851795/115140892-27d33f80-a06c-11eb-949d-1ab96eb8d7d2.png)
> 
> My cpu
> `$ cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c 32 Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`

The log shows that it cost almost 7 hours in the training stage. I guess that you're not using the GPU to run this process.

**Comment by Zilize** [comment]
> > Could you please provide the full log for this command? The data process step just cost 10 seconds on my machine.
> > <img alt="截屏2021-04-18 下午5 28 17" width="1161" src="https://user-images.githubusercontent.com/43633644/115140758-7e8c4980-a06b-11eb-8fec-744c4f7355f4.png">
> 
> Log
> ![image](https://user-images.githubusercontent.com/22851795/115140874-11c57f00-a06c-11eb-9348-8b6e7c7319a4.png)
> 
> cpu usage, this process exhaust all my cpus.
> ![image](https://user-images.githubusercontent.com/22851795/115140892-27d33f80-a06c-11eb-949d-1ab96eb8d7d2.png)
> 
> My cpu
> `$ cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c 32 Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`

The log shows that it cost almost 7 hours in the training stage. I guess that you're not using the GPU to run this process.

You can:

1. Run command "nvidia-smi" to ensure the process `29050` are running on the GPU;
2. If there isn't any process running on the GPU, you can run the following command to verify if the cuda toolkit is availble.

```
python -c "import torch; print(torch.cuda.is_available())"
```

**Comment by saladcat** [comment]
> > > Could you please provide the full log for this command? The data process step just cost 10 seconds on my machine.
> > > <img alt="截屏2021-04-18 下午5 28 17" width="1161" src="https://user-images.githubusercontent.com/43633644/115140758-7e8c4980-a06b-11eb-8fec-744c4f7355f4.png">
> > 
> > 
> > Log
> > ![image](https://user-images.githubusercontent.com/22851795/115140874-11c57f00-a06c-11eb-9348-8b6e7c7319a4.png)
> > cpu usage, this process exhaust all my cpus.
> > ![image](https://user-images.githubusercontent.com/22851795/115140892-27d33f80-a06c-11eb-949d-1ab96eb8d7d2.png)
> > My cpu
> > `$ cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c 32 Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz`
> 
> The log shows that it cost almost 7 hours in the training stage. I guess that you're not using the GPU to run this process.
> 
> You can:
> 
> 1. Run command "nvidia-smi" to ensure the process `29050` are running on the GPU;
> 2. If there isn't any process running on the GPU, you can run the following command to verify if the cuda toolkit is available.
> 
> ```
> python -c "import torch; print(torch.cuda.is_available())"
> ```

you are right!!!!!!
I has thought data process has no need of GPU, but it need.
Thank you
