### ISSUE TITLE
没有指定使用GPU，但是提示“ Torch not compiled with CUDA enabled”

### ISSUE THREAD

**Issue by bahaodangpu** [RUCAIBox/CRSLab#22]
运行代码：python run_crslab.py --config config/crs/kgsf/redial.yaml
提示的问题： Torch not compiled with CUDA enabled

**Comment by Jupaoqq** [comment]
crslab/system/base.py

Line 56: if opt["gpu"] == [-1]:
change -1 to 0 solves the problem
