### ISSUE TITLE
想问下TG-Redial和Redial中的conv_id是否是根据时间顺序生成的？

### ISSUE THREAD

**Issue by lisk123** [RUCAIBox/CRSLab#23]
以TG-Redial为例，每篇对话都有conv_id，请问下conv_id是随机生成的呢，还是按照时间顺序生成的？看到TG-Redial原文中写到，TG-Redial是根据豆瓣上真实用户的兴趣序列生成的，那么conv_id是否反应了用户兴趣随时间变化的趋势？

**Comment by Zyh716** [comment]
您好，TGReDial中，具有相同user_id的对话，conv_id越小，时间越早；不同user_id的对话之间，conv_id的大小与时间无关。
ReDial中，conv_id应该与时间无关。

**Comment by lisk123** [comment]
好的明白，感谢
