### ISSUE TITLE
can we download cc.en/cn.300.zip by other way? such as baidunetdisk. now it is too slow to download

### ISSUE THREAD

**Issue by WonderInvention** [RUCAIBox/CRSLab#29]

**Comment by xansar** [comment]
+1

**Comment by txy77** [comment]
Thanks for your feedback. However, there is a problem with Baidunetdisk. If we update the data on Baidunetdisk, the user must only download it manually. But onedrive allows users to update the latest version of the data on the netdisk without perception, which can greatly facilitate the users.
