### ISSUE TITLE
bert_param is alway none!

### ISSUE THREAD

**Issue by apprivoiser** [RUCAIBox/CRSLab#31]
https://github.com/RUCAIBox/CRSLab/blob/8b69dcbb8f8568244bb25f29f89bcd227e80d69c/crslab/system/tgredial.py#L169-L177

**Comment by Zilize** [comment]
It's not none when you run `config/recommendation/bert/*`. This is a flaw in our design which we will fix in next version.

**Comment by txy77** [comment]
Thanks for your feedback. We have already solved the problem. Now you can try again.
