### ISSUE TITLE
can't use cpu,maybe something wrong in config.py

### ISSUE THREAD

**Issue by leonyan18** [RUCAIBox/CRSLab#39]
in my opinion，I think maybe there is some problem in CRSLab/crslab/config/config.py  37
        # gpu
        os.environ['CUDA_VISIBLE_DEVICES'] = gpu
        self.opt['gpu'] = [i for i in range(len(gpu.split(',')))]
if gpu=-1，self.opt['gpu'] will be [0]

**Comment by txy77** [comment]
Thanks for your feedback. We have fixed this problem by considering the CPU training case separately, now you can try again.
