### ISSUE TITLE
Bugs in evaluator

### ISSUE THREAD

**Issue by Oran-Ac** [RUCAIBox/CRSLab#42]
When doing the `ind2txt`, we will get the `string`:
![image](https://user-images.githubusercontent.com/44745604/157155998-8dd21e2d-b7e5-4860-b310-9562b375ae81.png)
Then if we calculate the `n-gram`, it will get the **character** granularity of unique `n-gram`:
![image](https://user-images.githubusercontent.com/44745604/157156231-f1831779-da06-4cc5-95c5-959a7f59359e.png)
Example:
![image](https://user-images.githubusercontent.com/44745604/157156300-a17bf44f-5fb3-4654-8214-ba5cb9ad7330.png)
Correct:
![image](https://user-images.githubusercontent.com/44745604/157156384-a98ce4d0-f5e4-4f6a-ad81-1c6c39cc3aed.png)
code result:
![image](https://user-images.githubusercontent.com/44745604/157156560-798bf49f-cf68-44e9-a350-f8038a2dcb71.png)

**Comment by wxl1999** [comment]
Hi, @icedpanda, sorry for late reply. Thanks for your code, we will fix it soon.
I find the same phenomenon about the metric `dist@k`. After discussing with the author of KGSF, we think that it is a normal phenomenon. With the increase of training epochs, the metric will quickly increase too. You don't need to worry about that.
