### ISSUE TITLE
which dataset did NTRD use exactly?

### ISSUE THREAD

**Issue by dayuyang1999** [RUCAIBox/CRSLab#43]
Hi,

First, thank you for open-sourcing such a fantastic tool! It is a great job.

I have a small question about NTRD: which dataset did it use? It seems that I saw a conflict between the paper and the code here.
In the paper, authors said: "To evaluate the performance of our method, we conduct comprehensive experiments on the **REDIAL** dataset1, ......"
However, in the yaml file for NTRD, it clearly shows "**dataset: TGReDial**". 

**I am confused about which is the one that has been used to train NTRD? TGReDial or Redial?**

Thanks!

**Comment by dayuyang1999** [comment]
Thanks for answering my question via email.

**Comment by 1191000606** [comment]
您好，我也有同样的问题，可以请教一下吗

**Comment by wxl1999** [comment]
Hi, as our design, every model can be trained on any dataset.

**Comment by LQlq123** [comment]
> Hi,
> 
> First, thank you for open-sourcing such a fantastic tool! It is a great job.
> 
> I have a small question about NTRD: which dataset did it use? It seems that I saw a conflict between the paper and the code here. In the paper, authors said: "To evaluate the performance of our method, we conduct comprehensive experiments on the **REDIAL** dataset1, ......" However, in the yaml file for NTRD, it clearly shows "**dataset: TGReDial**".
> 
> **I am confused about which is the one that has been used to train NTRD? TGReDial or Redial?**
> 
> Thanks!

你好，我为NTRD模型创建了一个redial.yaml的配置文件，但是它一直报有replace_token的错误，请问是否可以借鉴一下您为NTRD创建的redial.yaml文件，万分感谢！
