### ISSUE TITLE
run_crslab.py: error: argument -i/--interact: ignored explicit argument 't'

### ISSUE THREAD

**Issue by ifty1987** [RUCAIBox/CRSLab#46]
when i run this script " !sh script/redial/train/redial_rec_train.sh" of c2crs, following error comes. please help

usr/local/lib/python3.7/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
usage: run_crslab.py [-h] [-c CONFIG] [-sd] [-rd] [-ss] [-rs] [-d] [-i]
run_crslab.py: error: argument -i/--interact: ignored explicit argument 't'

**Comment by txy77** [comment]
Maybe you could try the command following. 
python run_crslab.py --config config/crs/kgsf/redial.yaml

**Comment by wxl1999** [comment]
@ifty1987 Hi, you can also ask the author of c2crs @Zyh716 for help.
