### ISSUE TITLE
Preprocessing for Formatted Dataset

### ISSUE THREAD

**Issue by hvarS** [RUCAIBox/CRSLab#60]
The code for preprocessing that you have used for unifying the dataset format (specifically, *entity linking* and *BPE*) has not been given. Can you please let us know the algorithms/code used for the above mentioned processes? Since in the original dataset, (say DuRecDial), we don't get word and entity keys in the conversation which I assume are from HowNet and CN-DBPedia respectively.

![image](https://user-images.githubusercontent.com/34151780/195042619-2d276b39-0669-42cf-9b77-35d28477ee6c.png)

**Comment by wxl1999** [comment]
Thanks for your attention on our toolkit. Currently, we are testing the code of text tokenization. As for entity linking, the algorithm is complex so we do it offline, and we are trying to simplify this algorithm such that it can be processed on the fly.

**Comment by hvarS** [comment]
Thanks for the clearing this up! Secondly, in the **CRS** task, for each of the datasets, we get specific sub kg associated with that dataset. What is the code used for creating that subgraph ? Also is the algorithm for entity linking open-sourced?

**Comment by wxl1999** [comment]
1. To create the subgraph, following previous work, we extract the two hop neighbors of entities mentioned in the dialogue texts from the KG.
2. You can try official APIs or toolkits, such as DBpedia Spotlight. For those KGs without APIs or toolkits, we develop our own algorithm which is complex as mentioned before.

**Comment by hvarS** [comment]
Okay Thanks a lot !
