### ISSUE TITLE
About the evaluation metric dist@K

### ISSUE THREAD

**Issue by user-AC** [RUCAIBox/CRSLab#67]
Thanks for your amazing project！

I noticed that the dist@k obtained by using crslab is much larger than the dist@k reported in the original paper, such as kgsf, what is the reason?

Looking forward to your reply.

**Comment by wxl1999** [comment]
I do not find the reason either. If you have any idea, you can tell me and raise a PR!

**Comment by user-AC** [comment]
ok, thanks!
