### ISSUE TITLE
Missing implementation for data preprocessing

### ISSUE THREAD

**Issue by wangxieric** [RUCAIBox/CRSLab#71]
Hi,

I am aiming to extend the current datasets. However, it is missing the implementation of data preprocessing. 
Therefore, I would like to ask if this can be included in the new version?

Thanks

**Comment by lengshuiyu332** [comment]
We are currently working on it and plan to include the necessary implementation in the next release. You could keep an eye out for the upcoming version. However, we cannot provide a specific release time at this moment.

**Comment by invoker-LL** [comment]
> We are currently working on it and plan to include the necessary implementation in the next release. You could keep an eye out for the upcoming version. However, we cannot provide a specific release time at this moment.

Really looking forward to see the update.
