### ISSUE TITLE
Can't download redial data, file is not found.

### ISSUE THREAD

**Issue by guolipa** [RUCAIBox/CRSLab#72]
Download with the given url https://pkueducn-my.sharepoint.com/:u:/g/personal/franciszhou_pku_edu_cn/EdVnNcteOkpAkLdNL-ejvAABPieUd8jIty3r1jcdJvGLzw?download=1, but can't get data, 404 FILE NOT FOUND

**Comment by wxl1999** [comment]
We have updated all the download links. You can try again.
