### ISSUE TITLE
TGREDIAL数据集中的user2history文件里的"xxx/z":[yyyy,yyyyy,yyyyy,yyyyyyy,....]

### ISSUE THREAD

**Issue by LQlq123** [RUCAIBox/CRSLab#77]
请问，请问TGREDIAL数据集中的user2history文件里的"xxx/z":[yyyy,yyyyy,yyyyy,yyyyyyy,....]，这里的xxx、z、yyyy是有什么含义，如果xxx是用户id，那么为什么和train_data中的user_id不对应，并且加上z之后的含义是什么，不是非常清楚，感谢解答！

**Comment by wxl1999** [comment]
您好，xxx 应该是 conv_id，z 是 local_id（对应某一轮），yyyy 应该是 global_id（对应某个物品）

**Comment by LQlq123** [comment]
感谢您的回复！但是我还是有个问题，如果xxx表示的是conv_id，那么经过和train_data.json对照，发现conv_id为0、1、10的时候，它所对应的user_id都为0，同一用户的list不一致，是需要取并集得到用户的最终交互记录吗？

**Comment by wxl1999** [comment]
同一用户的list不一致，应该是因为时间，这个 list 对应原始交互数据中在当前对话发生之前的用户行为，不同对话的时间不一样，您可以再联系数据集作者确认一下

**Comment by LQlq123** [comment]
好的，非常感谢您的及时回复！
---- 回复的原邮件 ----
| 发件人 | Xiaolei ***@***.***> |
| 发送日期 | 2023年07月20日 10:56 |
| 收件人 | RUCAIBox/CRSLab ***@***.***> |
| 抄送人 | Qin ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [RUCAIBox/CRSLab] TGREDIAL数据集中的user2history文件里的"xxx/z":[yyyy,yyyyy,yyyyy,yyyyyyy,....] (Issue #77) |

同一用户的list不一致，应该是因为时间，这个 list 对应原始交互数据中在当前对话发生之前的用户行为，不同对话的时间不一样，您可以再联系数据集作者确认一下
