### ISSUE TITLE
how can i interact with the system? i tried to run 'run_crslab.py' with ' -i' ,but it doesn't work.

### ISSUE THREAD

**Issue by fishKoKo** [RUCAIBox/CRSLab#9]
...[finish data laod]
...[finish data preprocess]
...[build model KGSF]
...[build system KGSF]

over

**Comment by wxl1999** [comment]
Thanks for your feedback! Now the tookit only support interact with `tgredial` system. We will optimize and extend this ability to all the systems in the future version.

**Comment by fishKoKo** [comment]
> Thanks for your feedback! Now the tookit only support interact with `tgredial` system. We will optimize and extend this ability to all the systems in the future version.

cc.zh.300.zip 和 gpt2_en.zip 不能被下载

**Comment by YuanMa2018** [comment]
> Thanks for your feedback! Now the tookit only support interact with `tgredial` system. We will optimize and extend this ability to all the systems in the future version.

Thanks for your nice project, believe it is quite helpful, just wondering how does the interactive dialog work? could you please might give an example?

**Comment by wxl1999** [comment]
> cc.zh.300.zip 和 gpt2_en.zip 不能被下载

We have fixed this problem by changing all download links, now you can try again.

**Comment by wxl1999** [comment]
> Thanks for your nice project, believe it is quite helpful, just wondering how does the interactive dialog work? could you please might give an example?

Thanks for your feedback! Currently, we only support interact with the model `tgredial` using the data `tgredial`, you can try it by `python run_crslab.py --config config/crs/tgredial/tgredial.yaml --interact` with an untrained model, after training one, you can try by `python run_crslab.py --config config/crs/tgredial/tgredial.yaml --interact --restore_system`

**Comment by fishKoKo** [comment]
> > Thanks for your nice project, believe it is quite helpful, just wondering how does the interactive dialog work? could you please might give an example?
> 
> Thanks for your feedback! Currently, we only support interact with the model `tgredial` using the data `tgredial`, you can try it by `python run_crslab.py --config config/crs/tgredial/tgredial.yaml --interact` with an untrained model, after training one, you can try by `python run_crslab.py --config config/crs/tgredial/tgredial.yaml --interact --restore_system`

谢谢你们的工作。当我用tgredial数据集里原有的对话进行互动时，很多时候系统回复为空。

**Comment by wxl1999** [comment]
> 谢谢你们的工作。当我用tgredial数据集里原有的对话进行互动时，很多时候系统回复为空。
Sorry, interaction functionality is not perfect. 
It's not easy to solve, developers already have a plan but recently there is not enough time.
If you have ideas about this, we can have a discussion. Thanks for your feedback.

**Comment by fishKoKo** [comment]
请问，user2history.json文件里，"xxx/z":[yyyy,yyyyy,yyyyy,yyyyyyy,....]这里的xxx、z、yyyy是有什么含义

**Comment by Zilize** [comment]
> 请问，user2history.json文件里，"xxx/z":[yyyy,yyyyy,yyyyy,yyyyyyy,....]这里的xxx、z、yyyy是有什么含义

`xxx` refers to conversation id. `z` refers to utterance id. List of `yyy` refers to the list of entities related to the current user.

For example, `"0/7": [14559]` means that the user related to the `7`th utterance in conversation whose `conv_id` is `0` has a historical interaction sequence `[14559]`.

More details can be found in `crslab/data/dataset/tgredial/tgredial.py`. [Link](https://github.com/RUCAIBox/CRSLab/blob/a05730e8b2c03df278587be34923fa818945d4c4/crslab/data/dataset/tgredial/tgredial.py#L196)
